# Generated by Django 6.0.1 on 2026-01-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientPhone',
            new_name='PatientCommunication',
        ),
    ]
